# Generated by Django 3.2.4 on 2021-06-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanser', models.JSONField(default='', max_length=800)),
                ('moisturizer', models.JSONField(default='', max_length=800)),
                ('serum', models.JSONField(default='', max_length=800)),
                ('sunscreen', models.JSONField(default='', max_length=800)),
                ('name', models.CharField(default='', max_length=800)),
                ('details', models.CharField(default='', max_length=800)),
            ],
        ),
    ]
