# Generated by Django 3.1.2 on 2020-10-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scraper',
            new_name='Skincare',
        ),
    ]
