# Generated by Django 3.1.2 on 2020-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_api', '0004_auto_20201027_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skincare',
            name='result',
        ),
        migrations.AlterField(
            model_name='skincare',
            name='cleanser',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='moisturizer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='serum',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='sunscreen',
            field=models.CharField(max_length=1000),
        ),
    ]
