# Generated by Django 3.1.2 on 2020-10-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_api', '0005_auto_20201027_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincare',
            name='details',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AddField(
            model_name='skincare',
            name='name',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='cleanser',
            field=models.JSONField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='moisturizer',
            field=models.JSONField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='serum',
            field=models.JSONField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='skincare',
            name='sunscreen',
            field=models.JSONField(default='', max_length=800),
        ),
    ]
